name: Delete old workflow runs

on:
  workflow_dispatch:
  schedule:
    - cron: '55 19 * * *' # UTC時間（日本時間で午前4時55分）

jobs:
  delete-old-workflow-runs:
    runs-on: ubuntu-latest
#    timeout-minutes: 1 # 150件くらい
    timeout-minutes: 5 # 1000件だと間に合わないかも
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
      WORKFLOW: update_list.yml
      WORKFLOW2: delete_old_workflow_runs.yml

    steps:
      - run: gh workflow view "${WORKFLOW}"
      - run: |
          gh run list --workflow "${WORKFLOW}" --limit 1000 --json databaseId,status,createdAt --jq '.[] | select(.status == "completed") | select(.createdAt < (now-( 5 * 86400 ) | strftime("%Y-%m-%dT%H-%M-%SZ") )) | .databaseId' \
          | xargs -n 1 -I {} gh api -X DELETE repos/${REPOSITORY}/actions/runs/{}
        env:
          REPOSITORY: ${{ github.repository }}
      - run: gh workflow view "${WORKFLOW2}"
      - run: |
          gh run list --workflow "${WORKFLOW2}" --limit 1000 --json databaseId,status,createdAt --jq '.[] | select(.status == "completed") | select(.createdAt < (now-( 5 * 86400 ) | strftime("%Y-%m-%dT%H-%M-%SZ") )) | .databaseId' \
          | xargs -n 1 -I {} gh api -X DELETE repos/${REPOSITORY}/actions/runs/{}
        env:
          REPOSITORY: ${{ github.repository }}